// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc7Qsr_9VRgjO8smKPAgFc0tC_rGuZMik',
    appId: '1:79560673530:web:a8c2dcda2173ee62d9e143',
    messagingSenderId: '79560673530',
    projectId: 'location-tracker-f9f53',
    authDomain: 'location-tracker-f9f53.firebaseapp.com',
    storageBucket: 'location-tracker-f9f53.appspot.com',
    measurementId: 'G-X1KCL88346',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1Dfk2y0WG9l4RFzXYixM01T9dkivoFug',
    appId: '1:79560673530:android:b4b124165c9d5656d9e143',
    messagingSenderId: '79560673530',
    projectId: 'location-tracker-f9f53',
    storageBucket: 'location-tracker-f9f53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ1GZrzHqF0Ekcls7Ri5mPFgXugqqJp40',
    appId: '1:79560673530:ios:852d1bc0cd98b618d9e143',
    messagingSenderId: '79560673530',
    projectId: 'location-tracker-f9f53',
    storageBucket: 'location-tracker-f9f53.appspot.com',
    iosClientId: '79560673530-dolvebumia17s0j2miqm77skksqb9vsq.apps.googleusercontent.com',
    iosBundleId: 'id.inving.loctra.ios',
  );
}
